// const myArr = [0,1,2,3,4];
// const heros = ['hanuman','shaktiman','hulk'];
// const myArr2 = new Array(1,2,3,4,5,6,7,8);
// console.log(myArr);
// console.log(heros);
// console.log(myArr2);
// console.log(myArr.includes(4));
// console.log(myArr.indexOf(4));
// const newArr = myArr.join();
// console.log(typeof newArr);
// console.log('A',myArr);
// const sliceArr = myArr.slice(1,3);
// console.log('slice',sliceArr);
// console.log('B',myArr);
// const spliceArr = myArr.splice(1,3);
// console.log('splice',spliceArr);
// console.log('C',myArr);
const marvel =['hulk','ironman','thor','spiderman'];
const dc = ['superman','batman','flash','wonderwoman'];
// marvel.push(dc)
// console.log(marvel);
// const all_heros=marvel.concat(dc);
// console.log(all_heros);
// const heros = [...marvel,...dc];
// console.log(heros); 
// const myArr = [1,2,[3,4,5],[6,7,[8,9]]];
// console.log(myArr);
// const real_myArr = myArr.flat(Infinity);
// console.log(real_myArr);

console.log(Array.isArray('kajal'));
console.log(Array.from('kajal'));
console.log(Array.from({name:'kajal'}));
const score1 =100;
const score2 =200;
const score3 =300;
console.log(Array.of(score1,score2,score3));